version: 2.1
jobs:
  setup-runner:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    # resource_class: arm.large
    environment:
      ARCH: arm64
      # OR ARCH: x64
      # You should change the REPO to your own repository.
      # If no "/" is included, it is automatically recognized as an organization.
      REPO: 2moe/circle-runner
      # label="${LABEL_PREFIX}${ARCH}"
      LABEL_PREFIX: circle-
    steps:
      - run:
          name: build
          shell: sh -e
          command: |
              git clone https://github.com/ps3-pkgi/ps3toolchain/ 1
              cd 1
              bash toolchain.sh
workflows:
  download-and-run:
    jobs:
      - setup-runner:
          context: github
